"""Generate docs/data_profile.md from the downloaded CUAD data.

Usage:
    uv run python scripts/profile_cuad.py
"""

import statistics
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from clausewise.ingestion.cuad import load_cuad


def main() -> None:
    contracts = load_cuad()

    lengths = sorted(len(c.text) for c in contracts)
    clause_counts: Counter[str] = Counter()
    answered = 0
    unanswered = 0
    span_lengths: list[int] = []

    for contract in contracts:
        for ann in contract.annotations:
            clause_counts[ann.clause_type] += 1
            if ann.has_answer:
                answered += 1
                span_lengths.extend(len(s.text) for s in ann.spans)
            else:
                unanswered += 1

    total_ann = answered + unanswered

    def pct(part: int, whole: int) -> str:
        return f"{100 * part / whole:.1f}%"

    def quantile(data: list[int], q: float) -> int:
        return data[min(int(q * len(data)), len(data) - 1)]

    lines = [
        "# CUAD Data Profile",
        "",
        "Generated by `scripts/profile_cuad.py`. Do not edit by hand.",
        "",
        "## Corpus",
        "",
        f"- Contracts: **{len(contracts)}**",
        f"- Annotation rows (contract x clause type): **{total_ann}**",
        f"- Distinct clause types: **{len(clause_counts)}**",
        f"- Rows with ≥1 span: **{answered}** ({pct(answered, total_ann)})",
        f"- Rows with no answer: **{unanswered}** ({pct(unanswered, total_ann)}) "
        "→ refusal-evaluation pool",
        "",
        "## Contract text length (characters)",
        "",
        f"- min {lengths[0]:,} · p25 {quantile(lengths, 0.25):,} · "
        f"median {quantile(lengths, 0.5):,} · p75 {quantile(lengths, 0.75):,} · "
        f"p95 {quantile(lengths, 0.95):,} · max {lengths[-1]:,}",
        f"- mean {int(statistics.mean(lengths)):,}",
        "",
        "## Annotated span length (characters)",
        "",
        f"- median {int(statistics.median(span_lengths)):,} · "
        f"mean {int(statistics.mean(span_lengths)):,} · max {max(span_lengths):,}",
        "",
        "## Answered rows per clause type",
        "",
        "| Clause type | Contracts with ≥1 span |",
        "|---|---|",
    ]

    answered_by_type: Counter[str] = Counter()
    for contract in contracts:
        for ann in contract.annotations:
            if ann.has_answer:
                answered_by_type[ann.clause_type] += 1
    for clause_type, count in answered_by_type.most_common():
        lines.append(f"| {clause_type} | {count} |")

    out = Path("docs/data_profile.md")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
